/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users */
        get: operations["UsersController_getUsers"];
        put?: never;
        /** Create a new user */
        post: operations["UsersController_createUser"];
        /** Delete a user */
        delete: operations["UsersController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate user credentials */
        post: operations["UsersController_validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredient-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ingredient sets by user ID */
        get: operations["IngredientsController_getUserIngredientSets"];
        put?: never;
        /** Create a new ingredient set */
        post: operations["IngredientsController_createIngredientSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredient-sets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an ingredient set */
        patch: operations["IngredientsController_updateIngredientSet"];
        trace?: never;
    };
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recipes by user ID */
        get: operations["RecipeController_findByUserId"];
        put?: never;
        /** Save a recipe */
        post: operations["RecipeController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/rated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get rated recipes for prompt context */
        get: operations["RecipeController_getRatedRecipes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update recipe rating (1-5) */
        patch: operations["RecipeController_updateRating"];
        trace?: never;
    };
    "/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a recipe by ID */
        get: operations["RecipeController_findById"];
        put?: never;
        post?: never;
        /** Delete a recipe */
        delete: operations["RecipeController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserResponseDto: {
            /** @example 1 */
            id: number;
            /** @example user@example.com */
            email: string;
        };
        CreateUserDto: {
            /** @example user@example.com */
            email: string;
            /** @example password1 */
            password: string;
        };
        ValidateUserDto: {
            /** @example user@example.com */
            email: string;
            /** @example password1 */
            password: string;
        };
        DeleteUserDto: {
            /** @example 1 */
            id: number;
        };
        CreateIngredientDto: {
            /** @example 1 */
            userId: number;
            /**
             * @example [
             *       "tomato",
             *       "onion",
             *       "garlic"
             *     ]
             */
            ingredients: string[];
        };
        IngredientSetResponseDto: {
            /** @example 1 */
            id: number;
            /**
             * @example [
             *       "tomato",
             *       "onion",
             *       "garlic"
             *     ]
             */
            ingredients: string[];
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /** @example 1 */
            userId: number;
        };
        UpdateIngredientDto: {
            /**
             * @example [
             *       "tomato",
             *       "onion",
             *       "garlic"
             *     ]
             */
            ingredients: string[];
        };
        CreateRecipeDto: {
            /** @example 1 */
            userId: number;
            /** @example トマトパスタ */
            name: string;
            /**
             * @example ## トマトパスタの作り方
             *     ...
             */
            content: string;
            /**
             * @example [
             *       "トマト",
             *       "玉ねぎ",
             *       "にんにく"
             *     ]
             */
            ingredients: string[];
            /** @example 2 */
            servings: number;
            /**
             * @example [
             *       {
             *         "videoId": "abc",
             *         "title": "Recipe video",
             *         "channelTitle": "Channel",
             *         "thumbnail": "https://..."
             *       }
             *     ]
             */
            youtubeVideos?: Record<string, never> | null;
        };
        RecipeResponseDto: {
            /** @example 1 */
            id: number;
            /** @example トマトパスタ */
            name: string;
            /**
             * @example ## トマトパスタの作り方
             *     ...
             */
            content: string;
            /**
             * @example [
             *       "トマト",
             *       "玉ねぎ",
             *       "にんにく"
             *     ]
             */
            ingredients: string[];
            /** @example 2 */
            servings: number;
            /** @example null */
            youtubeVideos?: Record<string, never> | null;
            /** @example null */
            rating?: number | null;
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /** @example 1 */
            userId: number;
        };
        PaginatedRecipeResponseDto: {
            items: components["schemas"]["RecipeResponseDto"][];
            /** @example 10 */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    UsersController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteUserDto"];
            };
        };
        responses: {
            /** @description User deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_validate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateUserDto"];
            };
        };
        responses: {
            /** @description User validated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IngredientsController_getUserIngredientSets: {
        parameters: {
            query: {
                userId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of ingredient sets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientSetResponseDto"][];
                };
            };
        };
    };
    IngredientsController_createIngredientSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIngredientDto"];
            };
        };
        responses: {
            /** @description Ingredient set created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientSetResponseDto"];
                };
            };
        };
    };
    IngredientsController_updateIngredientSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIngredientDto"];
            };
        };
        responses: {
            /** @description Ingredient set updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientSetResponseDto"];
                };
            };
        };
    };
    RecipeController_findByUserId: {
        parameters: {
            query: {
                userId: number;
                page?: number;
                perPage?: number;
                search?: string;
                ratingFilter?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of recipes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecipeResponseDto"];
                };
            };
        };
    };
    RecipeController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecipeDto"];
            };
        };
        responses: {
            /** @description Recipe saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
        };
    };
    RecipeController_getRatedRecipes: {
        parameters: {
            query: {
                userId: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        rating: number;
                    }[];
                };
            };
        };
    };
    RecipeController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
        };
    };
    RecipeController_updateRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rating: number;
                };
            };
        };
        responses: {
            /** @description Rating updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
        };
    };
    RecipeController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
        };
    };
}
