/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users */
        get: operations["UsersController_getUsers"];
        put?: never;
        /** Create a new user */
        post: operations["UsersController_createUser"];
        /** Delete a user */
        delete: operations["UsersController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredient-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ingredient sets by user ID */
        get: operations["IngredientsController_getUserIngredientSets"];
        put?: never;
        /** Create a new ingredient set */
        post: operations["IngredientsController_createIngredientSet"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update an ingredient set */
        patch: operations["IngredientsController_updateIngredientSet"];
        trace?: never;
    };
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recipes by user ID */
        get: operations["RecipeController_findByUserId"];
        put?: never;
        /** Save a recipe */
        post: operations["RecipeController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/rated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get rated recipes for prompt context */
        get: operations["RecipeController_getRatedRecipes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a recipe by ID */
        get: operations["RecipeController_findById"];
        put?: never;
        post?: never;
        /** Delete a recipe */
        delete: operations["RecipeController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update recipe rating (1-5) */
        patch: operations["RecipeController_updateRating"];
        trace?: never;
    };
    "/recipes/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update recipe name and content */
        patch: operations["RecipeController_updateContent"];
        trace?: never;
    };
    "/youtube/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search YouTube videos */
        get: operations["YouTubeController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gemini/generate-recipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a recipe using Gemini AI */
        post: operations["GeminiController_generateRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gemini/recognize-ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recognize ingredients from an image */
        post: operations["GeminiController_recognizeIngredients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gemini/validate-ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate ingredients using Gemini AI */
        post: operations["GeminiController_validateIngredients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gemini/follow-up-recipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow-up question about a generated recipe */
        post: operations["GeminiController_followUpRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and get JWT token */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email address with token */
        post: operations["AuthController_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend verification email */
        post: operations["AuthController_resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password for authenticated user */
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset email */
        post: operations["AuthController_requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with token */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-email-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request email address change */
        post: operations["AuthController_requestEmailChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email change with token */
        post: operations["AuthController_verifyEmailChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserResponseDto: {
            /** @example 1 */
            id: number;
            /** @example user@example.com */
            email: string;
        };
        CreateUserDto: {
            /** @example user@example.com */
            email: string;
            /** @example password1 */
            password: string;
        };
        DeleteUserDto: {
            /** @example 1 */
            id: number;
        };
        CreateIngredientDto: {
            /**
             * @example [
             *       "tomato",
             *       "onion",
             *       "garlic"
             *     ]
             */
            ingredients: string[];
        };
        IngredientSetResponseDto: {
            /** @example 1 */
            id: number;
            /**
             * @example [
             *       "tomato",
             *       "onion",
             *       "garlic"
             *     ]
             */
            ingredients: string[];
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /** @example 1 */
            userId: number;
        };
        UpdateIngredientDto: {
            /**
             * @example [
             *       "tomato",
             *       "onion",
             *       "garlic"
             *     ]
             */
            ingredients: string[];
        };
        YouTubeVideoDto: {
            /** @example dQw4w9WgXcQ */
            videoId: string;
            /** @example トマトパスタの作り方 */
            title: string;
            /** @example 料理チャンネル */
            channelTitle: string;
            /** @example https://i.ytimg.com/vi/dQw4w9WgXcQ/mqdefault.jpg */
            thumbnail: string;
        };
        CreateRecipeDto: {
            /** @example トマトパスタ */
            name: string;
            /**
             * @example ## トマトパスタの作り方
             *     ...
             */
            content: string;
            /**
             * @example [
             *       "トマト",
             *       "玉ねぎ",
             *       "にんにく"
             *     ]
             */
            ingredients: string[];
            /** @example 2 */
            servings: number;
            /** @example 和食 */
            genre?: string | null;
            youtubeVideos?: components["schemas"]["YouTubeVideoDto"][] | null;
        };
        RecipeResponseDto: {
            /** @example 1 */
            id: number;
            /** @example トマトパスタ */
            name: string;
            /**
             * @example ## トマトパスタの作り方
             *     ...
             */
            content: string;
            /**
             * @example [
             *       "トマト",
             *       "玉ねぎ",
             *       "にんにく"
             *     ]
             */
            ingredients: string[];
            /** @example 2 */
            servings: number;
            /** @example 和食 */
            genre?: string | null;
            youtubeVideos?: components["schemas"]["YouTubeVideoDto"][] | null;
            /**
             * @description 1-5の5段階評価、未評価はnull
             * @example null
             */
            rating?: number | null;
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /** @example 1 */
            userId: number;
        };
        PaginatedRecipeResponseDto: {
            items: components["schemas"]["RecipeResponseDto"][];
            /** @example 10 */
            total: number;
        };
        RatedRecipeResponseDto: {
            /** @example トマトパスタ */
            name: string;
            /** @example 4 */
            rating: number | null;
        };
        UpdateRecipeRatingDto: {
            /**
             * @description 1-5の5段階評価
             * @example 4
             */
            rating: number;
        };
        UpdateRecipeContentDto: {
            /** @example 減塩トマトパスタ */
            name: string;
            /**
             * @example ## 材料（2人分）
             *     ...
             */
            content: string;
        };
        YouTubeSearchResponseDto: {
            videos: components["schemas"]["YouTubeVideoDto"][];
        };
        RatedRecipeDto: {
            name: string;
            rating: number;
        };
        GenerateRecipeDto: {
            preferredIngredients?: string[];
            allIngredients?: string[];
            ingredients?: string[];
            servings?: number;
            genre?: string;
            ratedRecipes?: components["schemas"]["RatedRecipeDto"][];
        };
        GenerateRecipeResponseDto: {
            /**
             * @example ## 材料（2人分）
             *     ...
             */
            recipe: string;
            /** @example トマトパスタ */
            recipeName: string;
        };
        RecognizeIngredientsDto: {
            image: string;
        };
        RecognizeIngredientsResponseDto: {
            /**
             * @example [
             *       "トマト",
             *       "玉ねぎ",
             *       "鶏もも肉"
             *     ]
             */
            ingredients: string[];
        };
        ValidateIngredientsDto: {
            newIngredients: string[];
            existingIngredients: string[];
        };
        ValidateIngredientResultDto: {
            /** @example トマト */
            name: string;
            /** @example true */
            isFood: boolean;
            /** @example null */
            similarTo: string | null;
        };
        ValidateIngredientsResponseDto: {
            results: components["schemas"]["ValidateIngredientResultDto"][];
        };
        FollowUpRecipeDto: {
            /**
             * @example ## 材料（2人分）
             *     ...
             */
            recipeContent: string;
            /** @example トマトパスタ */
            recipeName: string;
            /** @example 減塩バージョンにしてください */
            message: string;
        };
        FollowUpRecipeResponseDto: {
            /**
             * @example ## 材料（2人分）
             *     ...
             */
            recipe: string;
            /** @example 減塩トマトパスタ */
            recipeName: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        LoginResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
        };
        VerifyEmailDto: {
            /** @example abc123def456... */
            token: string;
        };
        ResendVerificationDto: {
            /** @example user@example.com */
            email: string;
        };
        ChangePasswordDto: {
            /** @example oldPassword1 */
            currentPassword: string;
            /** @example newPassword1 */
            newPassword: string;
        };
        ResetPasswordDto: {
            /** @example abc123def456... */
            token: string;
            /** @example newPassword1 */
            newPassword: string;
        };
        RequestEmailChangeDto: {
            /** @example new@example.com */
            newEmail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    UsersController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteUserDto"];
            };
        };
        responses: {
            /** @description User deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IngredientsController_getUserIngredientSets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of ingredient sets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientSetResponseDto"][];
                };
            };
        };
    };
    IngredientsController_createIngredientSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIngredientDto"];
            };
        };
        responses: {
            /** @description Ingredient set created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientSetResponseDto"];
                };
            };
        };
    };
    IngredientsController_updateIngredientSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIngredientDto"];
            };
        };
        responses: {
            /** @description Ingredient set updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientSetResponseDto"];
                };
            };
        };
    };
    RecipeController_findByUserId: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                search?: string;
                ratingFilter?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of recipes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecipeResponseDto"];
                };
            };
        };
    };
    RecipeController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecipeDto"];
            };
        };
        responses: {
            /** @description Recipe saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
        };
    };
    RecipeController_getRatedRecipes: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatedRecipeResponseDto"][];
                };
            };
        };
    };
    RecipeController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
        };
    };
    RecipeController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
        };
    };
    RecipeController_updateRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecipeRatingDto"];
            };
        };
        responses: {
            /** @description Rating updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
        };
    };
    RecipeController_updateContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecipeContentDto"];
            };
        };
        responses: {
            /** @description Recipe content updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
        };
    };
    YouTubeController_search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of YouTube videos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YouTubeSearchResponseDto"];
                };
            };
        };
    };
    GeminiController_generateRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRecipeDto"];
            };
        };
        responses: {
            /** @description Recipe generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateRecipeResponseDto"];
                };
            };
        };
    };
    GeminiController_recognizeIngredients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecognizeIngredientsDto"];
            };
        };
        responses: {
            /** @description Ingredients recognized */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecognizeIngredientsResponseDto"];
                };
            };
        };
    };
    GeminiController_validateIngredients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateIngredientsDto"];
            };
        };
        responses: {
            /** @description Ingredients validated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateIngredientsResponseDto"];
                };
            };
        };
    };
    GeminiController_followUpRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUpRecipeDto"];
            };
        };
        responses: {
            /** @description Follow-up reply generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUpRecipeResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email not verified */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            /** @description Email verified successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationDto"];
            };
        };
        responses: {
            /** @description Verification email sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            /** @description Password changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid current password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationDto"];
            };
        };
        responses: {
            /** @description Password reset email sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            /** @description Password reset successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_requestEmailChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestEmailChangeDto"];
            };
        };
        responses: {
            /** @description Verification email sent to new address */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already in use */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyEmailChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            /** @description Email changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
